// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhpSsme53NBMAYm_3adQRzq6PxTZ5VHjw',
    appId: '1:1022693944328:web:75f3e24c91545fc39635bd',
    messagingSenderId: '1022693944328',
    projectId: 'belivers-hub-gospel',
    authDomain: 'belivers-hub-gospel.firebaseapp.com',
    storageBucket: 'belivers-hub-gospel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDEHx58sYc60bfzntNeKy9jbiQsZIzeM0',
    appId: '1:1022693944328:android:59a627d4d6a0761b9635bd',
    messagingSenderId: '1022693944328',
    projectId: 'belivers-hub-gospel',
    storageBucket: 'belivers-hub-gospel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ5f6JydOgA8fUvcrGWp76e98S5jDOyHs',
    appId: '1:1022693944328:ios:d4fbe74cfe2f08359635bd',
    messagingSenderId: '1022693944328',
    projectId: 'belivers-hub-gospel',
    storageBucket: 'belivers-hub-gospel.firebasestorage.app',
    iosBundleId: 'com.belivershub.in.beliversHub',
  );
}
